### ISSUE TITLE
OpenMP bug

### ISSUE THREAD

**Issue by GlazerMann** [SNL-WaterPower/SNL-SWAN#4]
This code:
 integer, dimension(10) :: nacvt ! number of active vertices for i-th thread
in
SwanThreadBounds.ftn90 
means that all results for more than 10 OpenMP threads are wrong.  Please change to:

 integer, dimension(:), allocatable :: nacvt ! number of active vertices for i-th thread
.........
 allocate(nacvt(nth))
.........
 deallocate(nacvt)

Thank you.

**Comment by ccchart** [comment]
Agreed. Change made to latest push of "newmods" branch (executables not updated)
