### ISSUE TITLE
Obcase 3 not working

### ISSUE THREAD

**Issue by danielrajd** [SNL-WaterPower/SNL-SWAN#6]
I tried the example file found in the repository. Obcase 1 works fine however when I tried Obcase 3 the obstacle vanishes. Not able to understand why the varying transmission coefficient with power file is not working. Should I try to run the simulation in a different way?

**Comment by kmruehl** [comment]
@Danny10raj thanks for bringing this to our attention. We are looking into resolving this issue now. In the meantime, I recommend using the previous release of SNL-SWAN, [v1.0](https://github.com/SNL-WaterPower/SNL-SWAN/releases/tag/v1.0).

**Comment by kmruehl** [comment]
@Danny10raj  The bug with OBCASE 3 has been resolved with commit https://github.com/SNL-WaterPower/SNL-SWAN/commit/883de4167e84d2222bdf2bd9e9f4d58b0b75e46c. You should now be able to run OBCASE 3 and generate a (non-zero) POWER_ABS.OUT file without issue.
