### ISSUE TITLE
Obcase 4 not working

### ISSUE THREAD

**Issue by valefa93** [SNL-WaterPower/SNL-SWAN#7]
Dear SNL-SWAN users and developers,
I was running SNL-SWAN in a coastal area of Portugal in the presence of a wave farm and I realised that OBCASE 4 the devices were not absorbing energy (the POWER_ABS.OUT was zero for all of them). 
I tried to run the model with the input files from your tutorial and the same is happening, OBCASE 4 is not working. Can anyone help me understanding why?
I would really appreciate any help you can provide.
Best Regards,
Valeria Fanti

**Comment by kmruehl** [comment]
@valefa93 thanks for bringing this to our attention. We are looking into resolving this issue now. In the meantime, I recommend using the previous release of SNL-SWAN, [v1.0](https://github.com/SNL-WaterPower/SNL-SWAN/releases/tag/v1.0).

**Comment by kmruehl** [comment]
@valefa93 The bug with OBCASE 4 has been resolved with commit https://github.com/SNL-WaterPower/SNL-SWAN/commit/883de4167e84d2222bdf2bd9e9f4d58b0b75e46c. You should now be able to run OBCASE 4 and generate a (non-zero) POWER_ABS.OUT file without issue.
